version: '3'

services:
  web: 
    build: ./docker/web
    container_name: web
    ports:
        - 80:80
        - 443:443
    volumes:
      - ./data/home/apidae-event/www:/home/apidae-event/www
      - ./data/home/apidae-event/logs:/home/apidae-event/logs
      - ./docker/web/apidae-event.conf:/etc/apache2/sites-enabled/apidae-event.conf
      
      - ./data/home/git/www:/home/git/www
      - ./data/home/git/logs:/home/git/logs
      - ./docker/web/git.conf:/etc/apache2/sites-enabled/git.conf

      - ./data/home/admin/symfony:/home/admin/symfony
      - ./data/home/admin/logs:/home/admin/logs
      - ./docker/web/admin.conf:/etc/apache2/sites-enabled/admin.conf
      
      - ./data/home/md/www:/home/md/www
      - ./data/home/md/logs:/home/md/logs
      - ./docker/web/md.conf:/etc/apache2/sites-enabled/md.conf

      - ./data/home/roadmap/symfony:/home/roadmap/symfony
      - ./data/home/roadmap/logs:/home/roadmap/logs
      - ./docker/web/roadmap.conf:/etc/apache2/sites-enabled/roadmap.conf

      - ./data/home/demo/symfony:/home/demo/symfony
      - ./data/home/demo/logs:/home/demo/logs
      - ./docker/web/demo.conf:/etc/apache2/sites-enabled/demo.conf

      - ./data/srv/var/log/apache2:/var/log/apache2

      - ./docker/web/php.ini:/etc/php/7.4/apache2/conf.d/90-custom.ini
      - /etc/localtime:/etc/localtime:ro
      - ./docker/web/ssl-params.conf:/etc/apache2/conf-available/ssl-params.conf

    restart: unless-stopped
